title: Snowphlake Github page
page-top-title: Vikram Venkatraghavan
top-section-bg-text: Amsterdam UMC
home-subtitle: Trained machine-learning models for subtyping and estimating disease severity
copyright-text: '&copy; Sen Li 2023-2024. All Rights Reserved.'
